services:
  # The Flask Web Server
  - type: web
    name: appie-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app
    envVars:
      - key: MASTER_PASSWORD
        sync: false # Set this in the Render dashboard
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0

