name: AH Koopjes Collector

on:
  schedule:
    - cron: "*/1 7-20 * * *"
  # workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Libraries installeren
        run: pip install requests pandas

      - name: Script draaien
        run: python scheduling_AH.py

      - name: Data opslaan in de repo
        run: |
          git config user.name "BargainBot"
          git config user.email "bot@ah-tracker.com"
          git add koopjes_historie.csv
          git diff --cached --quiet && exit 0
          git commit -m "Update koopjes data"
          git push
